export const MEDICAL_SPECIALTIES = [
	"Allergy and Immunology",
	"Anesthesiology",
	"Cardiology",
	"Dermatology",
	"Emergency Medicine",
	"Endocrinology",
	"Family Medicine",
	"Gastroenterology",
	"Geriatrics",
	"Hematology",
	"Infectious Disease",
	"Internal Medicine",
	"Medical Genetics",
	"Nephrology",
	"Neurology",
	"Obstetrics and Gynecology",
	"Oncology",
	"Ophthalmology",
	"Orthopedics",
	"Otolaryngology",
	"Pathology",
	"Pediatrics",
	"Physical Medicine and Rehabilitation",
	"Plastic Surgery",
	"Psychiatry",
	"Pulmonology",
	"Radiology",
	"Rheumatology",
	"Sports Medicine",
	"Surgery",
	"Urology"
]


export const MEDICAL_UNITS = [

	"Accident and Emergency (A&E)",
	"Cardiology Unit",
	"Critical Care Unit (CCU)",
	"Dermatology Unit",
	"Endoscopy Unit",
	"Gastroenterology Unit",
	"General Surgery Unit",
	"Geriatrics Unit",
	"Gynecology Unit",
	"Hematology Unit",
	"Intensive Care Unit (ICU)",
	"Labor and Delivery Unit",
	"Maternity Unit",
	"Neonatal Intensive Care Unit (NICU)",
	"Nephrology Unit",
	"Neurology Unit",
	"Oncology Unit",
	"Ophthalmology Unit",
	"Orthopedic Unit",
	"Otolaryngology Unit",
	"Palliative Care Unit",
	"Pediatrics Unit",
	"Plastic Surgery Unit",
	"Psychiatry Unit",
	"Radiology Unit",
	"Rehabilitation Unit",
	"Renal Unit",
	"Respiratory Unit",
	"Rheumatology Unit",
	"Stroke Unit",
	"Thoracic Surgery Unit",
	"Trauma Unit",
	"Urology Unit",
	"Vascular Surgery Unit"



]
